# Generated by Django 3.0.3 on 2020-02-13 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('caption', models.CharField(max_length=500)),
                ('pubDate', models.DateTimeField(default=datetime.datetime(2020, 2, 13, 18, 25, 43, 7952), max_length=11)),
                ('imageFile', models.FileField(blank=True, null=True, upload_to='xander/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosAPI.User')),
            ],
        ),
    ]
