# Generated by Django 3.0.3 on 2020-02-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotosAPI', '0003_auto_20200214_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pubDate',
            field=models.DateTimeField(default='2020-02-14 04:32:00', max_length=11),
        ),
    ]
